#!/usr/bin/env bash
# Shared local setup, sourced by local-e2e.sh and local-lab.sh:
# two anvils (Sepolia stand-in :8545, Creditcoin stand-in :8546), every Kitty contract deployed,
# the credit pool seeded, the Attestcoin precompiles mocked with anvil_setCode, and web/.env.local
# written so `cd web && pnpm dev` runs the dashboard against this local world.
export KITTY_MODE=local
export SEPOLIA_RPC_URL=http://127.0.0.1:8545
export CREDITCOIN_RPC_URL=http://127.0.0.1:8546
export PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80   # anvil #0
export SOURCE_CHAIN_KEY=1
export PORT="${PORT:-8790}"

pkill -f "anvil --port 854[56]" 2>/dev/null || true
anvil --port 8545 --chain-id 11155111 --block-time 1 --silent &
anvil --port 8546 --chain-id 102031 --block-time 1 --silent &
sleep 2

deploy() { # <rpc> <path:Contract> [constructor args…]
  local rpc=$1 target=$2; shift 2
  forge create "$target" --rpc-url "$rpc" --private-key "$PRIVATE_KEY" --broadcast ${1+--constructor-args "$@"} 2>/dev/null \
    | grep -oE 'Deployed to: 0x[0-9a-fA-F]+' | cut -d' ' -f3
}

echo "== deploy (local)"
forge build >/dev/null
OP=$(cast wallet address --private-key "$PRIVATE_KEY")
USD=$(deploy "$SEPOLIA_RPC_URL" src/source/TestUSD.sol:TestUSD)
VAULT=$(deploy "$SEPOLIA_RPC_URL" src/source/KittyVault.sol:KittyVault "$USD" "$OP")
FAKE=$(deploy "$SEPOLIA_RPC_URL" src/source/FakeVault.sol:FakeVault)
LEDGER=$(deploy "$CREDITCOIN_RPC_URL" src/asc/KittyLedger.sol:KittyLedger 1)
VIEWER=$(deploy "$CREDITCOIN_RPC_URL" src/asc/KittyViewer.sol:KittyViewer "$LEDGER")
KUSD=$(deploy "$CREDITCOIN_RPC_URL" src/asc/KittyUSD.sol:KittyUSD)
CREDIT=$(deploy "$CREDITCOIN_RPC_URL" src/asc/KittyCreditLine.sol:KittyCreditLine "$LEDGER" "$KUSD")
BADGE=$(deploy "$CREDITCOIN_RPC_URL" src/asc/KittyBadge.sol:KittyBadge "$LEDGER")
for v in USD VAULT FAKE LEDGER VIEWER KUSD CREDIT BADGE; do [ -n "${!v}" ] || { echo "deploy failed: $v" >&2; exit 1; }; done
export TEST_USD_ADDRESS=$USD KITTY_VAULT_ADDRESS=$VAULT FAKE_VAULT_ADDRESS=$FAKE KITTY_LEDGER_ADDRESS=$LEDGER KITTY_VIEWER_ADDRESS=$VIEWER
export KITTY_USD_ADDRESS=$KUSD KITTY_CREDIT_ADDRESS=$CREDIT KITTY_BADGE_ADDRESS=$BADGE
echo "TestUSD $USD · KittyVault $VAULT · FakeVault $FAKE"
echo "KittyLedger $LEDGER · KittyViewer $VIEWER · KittyUSD $KUSD · KittyCreditLine $CREDIT · KittyBadge $BADGE"

echo "== trust the local vault on the ledger (per source chain)"
cast send --rpc-url $CREDITCOIN_RPC_URL --private-key $PRIVATE_KEY "$LEDGER" "setTrustedVault(uint64,address,bool)" "$SOURCE_CHAIN_KEY" "$VAULT" true >/dev/null

echo "== seed the credit pool: 100,000 kUSD minted, 50,000 deposited"
cast send --rpc-url $CREDITCOIN_RPC_URL --private-key $PRIVATE_KEY "$KUSD" "mint(address,uint256)" "$OP" 100000000000 >/dev/null
cast send --rpc-url $CREDITCOIN_RPC_URL --private-key $PRIVATE_KEY "$KUSD" "approve(address,uint256)" "$CREDIT" 50000000000 >/dev/null
cast send --rpc-url $CREDITCOIN_RPC_URL --private-key $PRIVATE_KEY "$CREDIT" "deposit(uint256)" 50000000000 >/dev/null

echo "== mock precompiles on the Creditcoin anvil"
cast rpc --rpc-url "$CREDITCOIN_RPC_URL" anvil_setCode 0x0000000000000000000000000000000000000FD2 "$(forge inspect MockVerifier deployedBytecode)" >/dev/null
cast rpc --rpc-url "$CREDITCOIN_RPC_URL" anvil_setCode 0x0000000000000000000000000000000000000fD3 "$(forge inspect MockChainInfo deployedBytecode)" >/dev/null
cast send --rpc-url "$CREDITCOIN_RPC_URL" --private-key "$PRIVATE_KEY" 0x0000000000000000000000000000000000000FD2 "setAccept(bool)" true >/dev/null

cat > web/.env.local <<ENV
# generated by scripts/local-setup.sh — delete this file to point the dashboard back at the testnets
VITE_SEPOLIA_RPC_URL=$SEPOLIA_RPC_URL
VITE_CREDITCOIN_RPC_URL=$CREDITCOIN_RPC_URL
VITE_SEPOLIA_CHAIN_ID=11155111
VITE_CREDITCOIN_CHAIN_ID=102031
VITE_LAB_API=http://localhost:$PORT
VITE_LEDGER_DEPLOY_BLOCK=1
VITE_TEST_USD_ADDRESS=$USD
VITE_KITTY_VAULT_ADDRESS=$VAULT
VITE_FAKE_VAULT_ADDRESS=$FAKE
VITE_KITTY_LEDGER_ADDRESS=$LEDGER
VITE_KITTY_VIEWER_ADDRESS=$VIEWER
VITE_KITTY_USD_ADDRESS=$KUSD
VITE_KITTY_CREDIT_ADDRESS=$CREDIT
VITE_KITTY_BADGE_ADDRESS=$BADGE
ENV
echo "wrote web/.env.local"
